# Generated by Django 3.2.9 on 2021-11-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
