# Generated by Django 3.2.10 on 2021-12-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0005_auto_20211126_1032'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('id', 'organisation')},
        ),
    ]
