# Generated by Django 3.2.10 on 2021-12-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0006_auto_20211207_1927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
