# Generated by Django 3.2.10 on 2021-12-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0007_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='primary_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroomapi.resource'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
