# Generated by Django 3.2.9 on 2022-01-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0009_auto_20220108_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'READY'), ('ERROR', 'ERROR')], default='READY', max_length=16),
        ),
        migrations.AlterField(
            model_name='link',
            name='max_link_type',
            field=models.CharField(choices=[('EVENT', 'Event'), ('RESOURCE', 'Resource'), ('CLIP', 'Clip'), ('COMMENT', 'Comment')], max_length=16),
        ),
        migrations.AlterField(
            model_name='link',
            name='min_link_type',
            field=models.CharField(choices=[('EVENT', 'Event'), ('RESOURCE', 'Resource'), ('CLIP', 'Clip'), ('COMMENT', 'Comment')], max_length=16),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('description', models.CharField(blank=True, max_length=60)),
                ('type', models.CharField(choices=[('SUBTITLE', 'Subtitle'), ('VIDEO_CLIP', 'Video Clip'), ('PDF_PAGE', 'PDF Page'), ('PDF_CLIP', 'PDF Clip'), ('NONE', 'None')], default='NONE', max_length=16)),
                ('start_location', models.IntegerField()),
                ('end_location', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomapi.course')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomapi.resource')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='anchor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroomapi.clip'),
        ),
    ]
