# Generated by Django 3.2.9 on 2022-01-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0011_alter_clip_end_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='end_location',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='primary_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroomapi.resource'),
        ),
        migrations.AlterField(
            model_name='link',
            name='anchor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroomapi.clip'),
        ),
    ]
