# Generated by Django 3.2.9 on 2022-01-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0012_auto_20220108_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='anchor',
        ),
        migrations.AlterField(
            model_name='clip',
            name='type',
            field=models.CharField(choices=[('VIDEO_CLIP', 'Video Clip'), ('PDF_PAGE', 'PDF Page'), ('PDF_CLIP', 'PDF Clip'), ('NONE', 'None')], default='NONE', max_length=16),
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('start_seconds', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomapi.course')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomapi.resource')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='subtitle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroomapi.subtitle'),
        ),
    ]
