# Generated by Django 3.2.9 on 2022-01-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0013_auto_20220108_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='max_link_id',
        ),
        migrations.RemoveField(
            model_name='link',
            name='max_link_type',
        ),
        migrations.RemoveField(
            model_name='link',
            name='min_link_id',
        ),
        migrations.RemoveField(
            model_name='link',
            name='min_link_type',
        ),
        migrations.AddField(
            model_name='link',
            name='max_link_clip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_link_clip', to='classroomapi.clip'),
        ),
        migrations.AddField(
            model_name='link',
            name='max_link_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_link_event', to='classroomapi.event'),
        ),
        migrations.AddField(
            model_name='link',
            name='max_link_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_link_resource', to='classroomapi.resource'),
        ),
        migrations.AddField(
            model_name='link',
            name='min_link_clip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='min_link_clip', to='classroomapi.clip'),
        ),
        migrations.AddField(
            model_name='link',
            name='min_link_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='min_link_event', to='classroomapi.event'),
        ),
        migrations.AddField(
            model_name='link',
            name='min_link_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='min_link_resource', to='classroomapi.resource'),
        ),
    ]
