# Generated by Django 3.2.9 on 2022-01-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0014_auto_20220108_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='subtitle_id',
            new_name='subtitle',
        ),
    ]
