# Generated by Django 3.2.10 on 2022-01-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0015_rename_subtitle_id_link_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroomapi.subtitle'),
        ),
    ]
