# Generated by Django 3.2.10 on 2022-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0016_alter_link_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
