# Generated by Django 3.2.10 on 2022-01-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0018_auto_20220121_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightrect',
            name='parent_rect',
        ),
        migrations.AddField(
            model_name='highlightrect',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroomapi.highlight'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='emoji',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
