# Generated by Django 3.2.10 on 2022-01-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0019_auto_20220121_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='highlight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroomapi.highlight'),
        ),
    ]
