# Generated by Django 3.2.10 on 2022-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0020_clip_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='content',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='course',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='title',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='type',
        ),
        migrations.AddField(
            model_name='clip',
            name='emoji',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
