# Generated by Django 3.2.10 on 2022-02-06 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroomapi', '0021_auto_20220122_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('ORGANISATION', 'Organisation'), ('COURSE', 'Course')], default='COURSE', max_length=16)),
                ('role', models.CharField(choices=[('STAFF', 'Staff'), ('STUDENT', 'Student')], default='STUDENT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomapi.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
