# Generated by Django 3.2.10 on 2022-02-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0023_auto_20220206_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroomapi.course'),
        ),
    ]
