# Generated by Django 3.2.10 on 2022-02-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapi', '0024_alter_membership_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classroomapi.resource'),
            preserve_default=False,
        ),
    ]
